### ISSUE TITLE
CLI execution with redirection to a file not working as expected

### ISSUE THREAD

**Issue by Yoanndp** [keraattin/EmailAnalyzer#16]
## Description:
When attempting to redirect the output of the email-analyzer.py script to a file, such as "`python3 email-analyzer.py file.eml > email.log`", an error is encountered. The error message reads:

```
Traceback (most recent call last):
  File "C:\Users\Yoanndp\Desktop\EmailAnalyzer\email-analyzer.py", line 201, in <module>
    description = str(get_introduction_banner())+"_"*TER_COL_SIZE
  File "C:\Users\Yoanndp\Desktop\EmailAnalyzer\banners.py", line 6, in get_introduction_banner
    print("""
  File "C:\Users\Yoanndp\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 14-25: character maps to <undefined>.
```

## Expected Behavior:
When executing the command "`python3 email-analyzer.py file.eml > email.log`", the output of the email-analyzer.py script should be redirected to the specified file "email.log" without any error.

## Observed Behavior:
When executing the command "`python3 email-analyzer.py file.eml > email.log`", the output is not redirected to the specified file, and the following error is encountered:

```
UnicodeEncodeError: 'charmap' codec can't encode characters in position 14-25: character maps to <undefined>.
```

## Steps to Reproduce:
1. Open a terminal or command prompt
2. Navigate to the directory containing the email-analyzer.py script and an email file (file.eml)
3. Execute the command "`python3 email-analyzer.py file.eml > email.log`"
4. Observe the error message displayed in the terminal.

## Environment:
- Operating System: Windows 10 21H2
- Python Version: 3.10.11

**Comment by keraattin** [comment]
First of all thank you for the noticing that issue. I do some research about the issue.
I think the problem is caused by the windows terminal you are using.  The windows terminals not open files with UTF-8 formatted as default and the **printing headers** in the app is not compatible with defaults.

I found a temporary solution for windows terminals, you should set IO encoding defaults to UTF-8:

- Enter this code after you opened your terminal `set PYTHONIOENCODING=utf-8`
- Than run your code `python email-analyzer.py -f file.eml > email.log`

PS: The command that you are using perfectly worked in other linux terminals.

### Additionally 
I added new features in the development branch. 

You can use **-o** parameter for the specifying output file
`python email-analyzer.py -f file.eml -o report.html`
or
`python email-analyzer.py -f file.eml -o report.json`

You specify the output file and you will get **JSON** or **HTML** formatted reports.

**Comment by Yoanndp** [comment]
Hello, thanks for your response. I tried the `set PYTHONIOENCODING=utf-8` trick, but it didn't work. However, switching to the dev branch and using the -o flag works. While waiting for the merge to master, I'll use the dev branch, thanks again!
